#
#
#       DO NOT EDIT THIS FILE !!!
#
#

from ROBOTS.ROBOT_P2_CONFIG import *

# CONTROL TABLE
ADDR_TORQUE_ENABLE          = 64
ADDR_GOAL_POSITION          = 116
ADDR_PRESENT_POSITION       = 132
ADDR_MOVING_SPEED           = 112

# BYTE SIZE INSTRUCTIONS
LEN_GOAL_POSITION           = 4
LEN_PRESENT_POSITION        = 4
LEN_MOVING_SPEED            = 4

# LIBRARIES
from dynamixel_sdk import *

# HANDLERS DEFINITION
portHandler = PortHandler(DEVICENAME)
packetHandler = PacketHandler(PROTOCOL_VERSION)

# SYNCS
groupSyncWritePosition = GroupSyncWrite(portHandler, packetHandler, ADDR_GOAL_POSITION, LEN_GOAL_POSITION)
groupSyncWriteSpeed = GroupSyncWrite(portHandler, packetHandler, ADDR_MOVING_SPEED, LEN_MOVING_SPEED)

groupSyncReadPosition = GroupSyncRead(portHandler, packetHandler, ADDR_PRESENT_POSITION, LEN_PRESENT_POSITION)

#COMMUNIACATION
def startCom():
    if portHandler.openPort():
        print("Succeeded to open the port")
    else:
        print("Failed to open the port")
        print("Press any key to terminate...")

    if portHandler.setBaudRate(BAUDRATE):
        print("Succeeded to change the baudrate")
    else:
        print("Failed to change the baudrate")
        print("Press any key to terminate...")

def stopCom():
        portHandler.closePort()
